[profile.default]
solc = '0.8.15'
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
test = 'test/foundry'
remappings = [
    'forge-std=lib/forge-std/src/',
    'contracts/=contracts/',
]

# See more config options https://github.com/gakonst/foundry/tree/master/config